# Dockerfile for raptor-web development
# This image does NOT build the app's code into the image.
# It instead relies on paths to local files in docker-compose-dev.yml
# Use docker-compose.yml for production.

FROM continuumio/miniconda3:latest

# Install host dependencies
RUN apt update
RUN apt install libmariadb-dev -y
RUN apt install gcc -y

# Copy Conda environment and install environment
COPY environment.yml environment.yml
RUN conda env create

# Add initialization script and define entrypoint
ADD docker/init init
RUN chmod +x+r -R init
ENTRYPOINT ["/init/run-raptorapp.sh"]
