# Generated by Django 4.2.7 on 2024-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="panellogentry",
            name="date",
            field=models.DateTimeField(auto_now_add=True, default="2024-06-04 00:00"),
            preserve_default=False,
        ),
    ]
