# Generated by Django 4.2.7 on 2024-06-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_panellogentry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="panellogentry",
            name="action",
            field=models.CharField(default="NewValue", max_length=50),
            preserve_default=False,
        ),
    ]
