# Generated by Django 4.1.5 on 2023-02-13 02:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField(default=0, help_text='The amount of players that were on this server the last time it was queried. Will always be zero if ENABLE_SERVER_QUERY is False.', verbose_name='Player Count')),
                ('announcement_count', models.IntegerField(default=0, help_text='The amount of announcements that were made for this server and retrieved by the Discord Bot. Only relevant if SCRAPE_SERVER_ANNOUNCEMENT is True and the Discord Bot is running..', verbose_name='Announcement Count')),
                ('server_state', models.BooleanField(default=False, help_text='Indicates whether a server is online or offline, based on the status of the query to the provided Domain Name/Port. Only relevant if ENABLE_SERVER_QUERY is enabled in .env settings.', verbose_name='Online/Offline')),
                ('in_maintenance', models.BooleanField(default=False, help_text="If this is enabled, this server will not have it's Domain Name/Port queried for player/state information, and its status indicator on the website will be replaced with a yellow 'Maintenance' indicator.", verbose_name='Maintenance Mode')),
                ('server_address', models.CharField(default='Default', help_text='The address/domain name used to connect to your server and query it. This is used by the application to query the server, and is also displayed on the website for users to copy.', max_length=50, verbose_name='Server Address/Domain Name')),
                ('server_port', models.IntegerField(default=0, help_text='The network port used to query your server by the application. This is not used on the website, it is only used to query information on the server.', verbose_name='Server Port')),
                ('modpack_name', models.CharField(default='Unnamed Modpack', help_text='The human-readable name of the modpack you are hosting on this server.', max_length=100, verbose_name='Modpack Name')),
                ('modpack_version', models.CharField(default='1.0', help_text='The version of the modpack you are hosting on this server.', max_length=100, verbose_name='Modpack Version')),
                ('modpack_description', ckeditor.fields.RichTextField(default='Modpack Description', help_text='A description of the modpack you are hosting on this server. Generally should describe the gameplay of the modpack itself.', max_length=1500, verbose_name='Modpack Description')),
                ('server_description', ckeditor.fields.RichTextField(default='Server Description', help_text='A description of the features that this particular server has.', max_length=1500, verbose_name='Server Description')),
                ('server_rules', ckeditor.fields.RichTextField(default='Server-specific Rules', help_text='Rules that are specific to this server.', max_length=1500, verbose_name='Server-Specific Rules')),
                ('server_banned_items', ckeditor.fields.RichTextField(default='Server-specific Banned Items', help_text='Items that are banned from being used on this server.', max_length=1500, verbose_name='Server-specific Banned Items')),
                ('server_vote_links', ckeditor.fields.RichTextField(default='Server-specific Vote Links', help_text='A list of links to forum/vote listings for this server.', max_length=1500, verbose_name='Voting Site Links')),
                ('modpack_picture', models.ImageField(blank=True, help_text='An image associated with this modpack that will be displayed on the website. The optimal size for this image is 820x200, where the image is wider than it is tall, but you can use any size image.', upload_to='modpack_pictures', verbose_name='Modpack Image')),
                ('modpack_url', models.URLField(help_text='A URL to the website where this modpack can be downloaded from.', verbose_name='Link to Modpack Page')),
                ('discord_announcement_channel_id', models.CharField(default='0', help_text='The Channel ID of the Discord Channel that will act as the Announcement channel for this server.', max_length=200, verbose_name='Discord Announcement Channel ID')),
                ('discord_modpack_role_id', models.CharField(default='0', help_text="The Role ID of the Discord Role that will act as the 'Ping Role' for this server. When this Role is 'pinged' in the Discord Announcement Channel for this server, that message will be considered an announcement for this server.", max_length=200, verbose_name='Discord Modpack Role ID')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='ServerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gameservers-stat', max_length=150)),
                ('total_player_count', models.IntegerField(default=0)),
                ('time_last_polled', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('server', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameservers.server')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
