# Generated by Django 4.1.5 on 2023-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatistic',
            options={'verbose_name': 'Server Statistics', 'verbose_name_plural': 'Server Statistics'},
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='total_player_count',
            field=models.IntegerField(default=0, verbose_name='Total Player Count'),
        ),
    ]
