# Generated by Django 3.2.5 on 2023-01-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='discord_role_id',
            field=models.CharField(default='None', max_length=200, verbose_name='Discord Role ID'),
        ),
    ]
