# Generated by Django 4.1.5 on 2023-02-12 22:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='discord_announcement_channel_id',
            field=models.CharField(default='0', help_text='The Channel ID of the Discord Channel that will act as the Announcement channel for this server.', max_length=200, verbose_name='Discord Announcement Channel ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='discord_modpack_role_id',
            field=models.CharField(default='0', help_text="The Role ID of the Discord Role that will act as the 'Ping Role' for this server. When this Role is 'pinged' in the Discord Announcement Channel for this server, that message will be considered an announcement for this server.", max_length=200, verbose_name='Discord Modpack Role ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='in_maintenance',
            field=models.BooleanField(default=False, help_text="If this is enabled, this server will not have it's Domain Name/Port queried for player/state information, and its status indicator on the website will be replaced with a yellow 'Maintenance' indicator.", verbose_name='Maintenance Mode'),
        ),
        migrations.AlterField(
            model_name='server',
            name='modpack_description',
            field=ckeditor.fields.RichTextField(default='Modpack Description', help_text='A description of the modpack you are hosting on this server. Generally should describe the gameplay of the modpack itself.', max_length=1500, verbose_name='Modpack Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='modpack_name',
            field=models.CharField(default='Unnamed Modpack', help_text='The human-readable name of the modpack you are hosting on this server.', max_length=100, verbose_name='Modpack Name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='modpack_picture',
            field=models.ImageField(blank=True, help_text='An image associated with this modpack that will be displayed on the website. The optimal size for this image is 820x200, where the image is wider than it is tall, but you can use any size image.', upload_to='modpack_pictures', verbose_name='Modpack Image'),
        ),
        migrations.AlterField(
            model_name='server',
            name='modpack_url',
            field=models.URLField(help_text='A URL to the website where this modpack can be downloaded from.', verbose_name='Link to Modpack Page'),
        ),
        migrations.AlterField(
            model_name='server',
            name='modpack_version',
            field=models.CharField(default='1.0', help_text='The version of the modpack you are hosting on this server.', max_length=100, verbose_name='Modpack Version'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_address',
            field=models.CharField(default='Default', help_text='The address/domain name used to connect to your server and query it. This is used by the application to query the server, and is also displayed on the website for users to copy.', max_length=50, verbose_name='Server Address/Domain Name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_banned_items',
            field=ckeditor.fields.RichTextField(default='Server-specific Banned Items', help_text='Items that are banned from being used on this server.', max_length=1500, verbose_name='Server-specific Banned Items'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_description',
            field=ckeditor.fields.RichTextField(default='Server Description', help_text='A description of the features that this server particular has.', max_length=1500, verbose_name='Server Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_port',
            field=models.IntegerField(default=0, help_text='The network port used to query your server by the application. This is not used on the website, it is only used to query information on the server.', verbose_name='Server Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_rules',
            field=ckeditor.fields.RichTextField(default='Server-specific Rules', help_text='Rules that are specific to this server.', max_length=1500, verbose_name='Server-Specific Rules'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_state',
            field=models.BooleanField(default=False, help_text='Indicates whether a server is online or offline, based on the status of the query to the provided Domain Name/Port. Only relevant if ENABLE_SERVER_QUERY is enabled in .env settings.', verbose_name='Online/Offline'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_vote_links',
            field=ckeditor.fields.RichTextField(default='Server-specific Vote Links', help_text='A list of links to forum/vote listings for this server.', max_length=1500, verbose_name='Voting Site Links'),
        ),
    ]
