# Generated by Django 4.1.5 on 2023-02-12 22:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0002_alter_server_discord_announcement_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_description',
            field=ckeditor.fields.RichTextField(default='Server Description', help_text='A description of the features that this particular server has.', max_length=1500, verbose_name='Server Description'),
        ),
    ]
