# Generated by Django 4.1.5 on 2023-02-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0002_alter_serverstatistic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='modpack_description',
            field=models.CharField(default='Modpack Description', help_text='A description of the modpack you are hosting on this server. Generally should describe the gameplay of the modpack itself.', max_length=1500, verbose_name='Modpack Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_banned_items',
            field=models.CharField(default='Server-specific Banned Items', help_text='Items that are banned from being used on this server.', max_length=1500, verbose_name='Server-specific Banned Items'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_description',
            field=models.CharField(default='Server Description', help_text='A description of the features that this particular server has.', max_length=1500, verbose_name='Server Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_rules',
            field=models.CharField(default='Server-specific Rules', help_text='Rules that are specific to this server.', max_length=1500, verbose_name='Server-Specific Rules'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_vote_links',
            field=models.CharField(default='Server-specific Vote Links', help_text='A list of links to forum/vote listings for this server.', max_length=1500, verbose_name='Voting Site Links'),
        ),
    ]
