# Generated by Django 4.2.7 on 2023-11-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0003_server_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
