# Generated by Django 4.1.5 on 2023-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0003_auto_20230121_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='discord_modpack_role_id',
            field=models.CharField(default='0', max_length=200, verbose_name='Discord Modpack Role ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='discord_announcement_channel_id',
            field=models.CharField(default='0', max_length=200, verbose_name='Discord Announcment Channel ID'),
        ),
    ]
