# Generated by Django 4.1.5 on 2023-01-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0004_server_discord_modpack_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='discord_announcement_channel_id',
            field=models.CharField(default='0', max_length=200, verbose_name='Discord Announcement Channel ID'),
        ),
    ]
