# Generated by Django 4.2.7 on 2023-11-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0004_player_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Online'),
        ),
    ]
