# Generated by Django 4.2.7 on 2023-11-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0005_player_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='gameservers.server'),
        ),
        migrations.CreateModel(
            name='PlayerCountHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField(verbose_name='Players Online')),
                ('checked_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of Query')),
                ('server', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameservers.server')),
            ],
            options={
                'verbose_name': 'Historic Player Count',
                'verbose_name_plural': 'Historic Player Counts',
            },
        ),
    ]
