# Generated by Django 4.2.7 on 2023-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0007_alter_server_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='announcement_count',
            field=models.IntegerField(default=0, help_text='The amount of announcements that were made for this server and retrieved by the Discord Bot. ', verbose_name='Announcement Count'),
        ),
    ]
