# Generated by Django 4.2.7 on 2023-11-19 00:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0009_alter_server_modpack_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='modpack_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='An image associated with this modpack that will be displayed on the website. The optimal size for this image is 820x200, where the image is wider than it is tall, but you can use any size image.', keep_meta=False, quality=80, scale=None, size=[545, 130], upload_to='modpack_pictures', verbose_name='Modpack Image'),
        ),
    ]
