# Generated by Django 4.2.7 on 2023-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0011_server_rcon_address_server_rcon_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='rcon_address',
            field=models.CharField(blank=True, default='', help_text='The IP address used to send RCON commands to this server.', max_length=200, null=True, verbose_name='RCON Connection Address'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rcon_password',
            field=models.CharField(blank=True, default='', help_text='The password used to authenticate when sending RCON commands to this server.', max_length=500, null=True, verbose_name='RCON Connection Password'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rcon_port',
            field=models.IntegerField(blank=True, default=0, help_text='The network port used to send RCON commands to this server.', null=True, verbose_name='RCON Connection Port'),
        ),
    ]
