# Generated by Django 4.2.7 on 2024-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gameservers",
            "0012_alter_server_rcon_address_alter_server_rcon_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="modpack_url",
            field=models.URLField(
                blank=True,
                help_text="A URL to the website where this modpack can be downloaded from.",
                null=True,
                verbose_name="Link to Modpack Page",
            ),
        ),
    ]
