# Generated by Django 4.2.7 on 2024-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameservers", "0014_player_first_joined"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="server",
            options={
                "permissions": [
                    ("maintenance_server", "Can toggle a server's maintenance status."),
                    ("archive_server", "Can toggle a server's archive status."),
                    ("importexport_server", "Can access the Server Import/Export menu"),
                ],
                "verbose_name": "Server",
                "verbose_name_plural": "Servers",
            },
        ),
    ]
