# Generated by Django 4.2.7 on 2025-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameservers", "0016_alter_server_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="use_modpack_description",
            field=models.BooleanField(
                default=True,
                help_text="If this is unchecked, the Modpack Description element will not appear in the server modal at all.",
                verbose_name="Use Modpack Description",
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="use_server_description",
            field=models.BooleanField(
                default=True,
                help_text="If this is unchecked, the Server Description element will not appear in the server modal at all.",
                verbose_name="Use Server Description",
            ),
        ),
    ]
