# Generated by Django 3.2.5 on 2022-12-16 08:13

import authprofiles.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUserInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('username', models.CharField(default='Default', max_length=100)),
                ('profile_picture', models.CharField(max_length=100)),
                ('pub_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('date_joined', models.DateTimeField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('minecraft_username', models.CharField(blank=True, max_length=50)),
                ('favorite_modpack', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'User - Discord OAuth',
                'verbose_name_plural': 'Users - Discord OAuth',
            },
            managers=[
                ('objects', authprofiles.managers.DiscordAuthManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('minecraft_username', models.CharField(blank=True, max_length=50)),
                ('favorite_modpack', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User - Extra Information',
                'verbose_name_plural': 'Users - Extra Information',
            },
        ),
    ]
