# Generated by Django 4.1.5 on 2023-01-26 00:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authprofiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaptorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discord_user_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authprofiles.discorduserinfo')),
                ('user_profile_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authprofiles.userprofileinfo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
