# Generated by Django 4.2.5 on 2023-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raptoruser',
            name='toasts_seen',
            field=models.JSONField(default=dict, help_text='JSON data representing which Notification Toasts this user has seen', verbose_name='Seen Notifications'),
        ),
    ]
