# Generated by Django 4.1.5 on 2023-01-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0002_raptoruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduserinfo',
            name='favorite_modpack',
        ),
        migrations.RemoveField(
            model_name='discorduserinfo',
            name='minecraft_username',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
