# Generated by Django 4.2.5 on 2023-10-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0002_raptoruser_toasts_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduserinfo',
            name='tag',
            field=models.CharField(help_text='The Discord username associated with this model.', max_length=100, verbose_name='Discord Tag'),
        ),
    ]
