# Generated by Django 4.2.7 on 2023-11-19 00:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0004_alter_userprofileinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text="A user's profile picture, uploaded and stored locally.", keep_meta=False, quality=50, scale=None, size=[150, 150], upload_to='profile_pictures', verbose_name='Profile Picture'),
        ),
    ]
