# Generated by Django 4.2.7 on 2024-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0005_alter_userprofileinfo_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileinfo",
            name="hidden_from_public",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this user appears on the user list, and whether their profile is publicly accessible.",
                null=True,
                verbose_name="Hidden from Public",
            ),
        ),
    ]
