# Generated by Django 4.1.5 on 2023-01-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0006_alter_raptoruser_discord_user_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduserinfo',
            options={'verbose_name': 'User - Discord Information', 'verbose_name_plural': 'Users - Discord Information'},
        ),
        migrations.RemoveField(
            model_name='discorduserinfo',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='discorduserinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='discorduserinfo',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='discorduserinfo',
            name='username',
        ),
    ]
