# Generated by Django 4.2.7 on 2024-05-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0007_raptoruser_date_queued_for_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raptoruser',
            name='date_queued_for_delete',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Queued for Deletion'),
        ),
    ]
