# Generated by Django 4.1.5 on 2023-01-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0008_raptoruser_is_discord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='raptoruser',
            name='user_slug',
            field=models.SlugField(null=True),
        ),
    ]
