# Generated by Django 4.2.7 on 2024-05-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0008_alter_raptoruser_date_queued_for_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raptoruser',
            name='toasts_seen',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data representing which Notification Toasts this user has seen', null=True, verbose_name='Seen Notifications'),
        ),
    ]
