# Generated by Django 4.1.5 on 2023-02-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0009_raptoruser_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raptoruser",
            name="discord_user_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discordinfo",
                to="authprofiles.discorduserinfo",
            ),
        ),
        migrations.AlterField(
            model_name="raptoruser",
            name="user_profile_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profileinfo",
                to="authprofiles.userprofileinfo",
            ),
        ),
    ]
