# Generated by Django 4.2.7 on 2024-05-28 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0009_alter_raptoruser_toasts_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeleteQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(blank=True, help_text='List of users that have requested to be deleted.', to=settings.AUTH_USER_MODEL, verbose_name='User Deletion Queue')),
            ],
        ),
    ]
