# Generated by Django 4.2.7 on 2024-05-28 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0010_userdeletequeue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionQueueForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDeleteQueue',
        ),
    ]
