# Generated by Django 4.1.5 on 2023-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0011_discorduserinfo_avatar_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raptoruser',
            name='is_discord_user',
            field=models.BooleanField(default=False),
        ),
    ]
