# Generated by Django 4.2.7 on 2024-05-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0011_deletionqueueforuser_delete_userdeletequeue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deletionqueueforuser",
            options={
                "verbose_name": "Users Queued for Deletion",
                "verbose_name_plural": "Users Queued for Deletion",
            },
        ),
    ]
