# Generated by Django 4.2.7 on 2024-05-28 13:33

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authprofiles", "0012_alter_deletionqueueforuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaptorUserGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
            },
            bases=("auth.group",),
            managers=[("objects", django.contrib.auth.models.GroupManager()),],
        ),
    ]
