# Generated by Django 4.2.7 on 2024-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0013_raptorusergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="raptoruser",
            name="totp_token",
            field=models.BinaryField(
                blank=True,
                default=None,
                editable=True,
                null=True,
                verbose_name="User TOTP Token",
            ),
        ),
    ]
