# Generated by Django 4.2.7 on 2024-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0014_raptoruser_totp_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="raptoruser",
            name="totp_qr",
            field=models.ImageField(
                blank=True,
                help_text="A QR code for setting up TOTP, stored temporarily",
                null=True,
                upload_to="totp",
                verbose_name="TOTP Setup QR",
            ),
        ),
    ]
