# Generated by Django 4.2.7 on 2024-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0016_remove_raptoruser_totp_qr_raptoruser_totp_qr_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="raptoruser",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if a user has MFA enabled on their account.",
                verbose_name="MFA Enabled",
            ),
        ),
    ]
