# Generated by Django 4.2.7 on 2024-07-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authprofiles", "0017_raptoruser_mfa_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raptoruser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
