# Generated by Django 3.2.5 on 2022-12-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(editable=False, verbose_name='Applicant age')),
                ('time', models.CharField(editable=False, max_length=500, verbose_name='Time Zone and alottable time')),
                ('mc_name', models.CharField(editable=False, max_length=500, verbose_name='Minecraft Username')),
                ('discord_name', models.CharField(editable=False, max_length=500, verbose_name='Discord Username/ID')),
                ('voice_chat', models.BooleanField(editable=False, max_length=500, verbose_name='Capable of using Voice Chat?')),
                ('description', models.TextField(editable=False, max_length=500, verbose_name='General self-description')),
                ('modpacks', models.TextField(editable=False, max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft')),
                ('experience', models.TextField(editable=False, max_length=500, verbose_name='Experience on other servers')),
                ('why_join', models.TextField(editable=False, max_length=500, verbose_name='Reasons for wanting to be staff.')),
            ],
        ),
        migrations.CreateModel(
            name='AdminApplication',
            fields=[
                ('staffapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staffapps.staffapplication')),
                ('position', models.CharField(default='Admin', editable=False, max_length=100)),
                ('plugins', models.TextField(editable=False, max_length=500, verbose_name='Knowledge of plugins/server mods and adaptability')),
                ('api', models.TextField(editable=False, max_length=500, verbose_name='Knowledge of server APIs and Minecraft proxies.')),
                ('it_knowledge', models.TextField(editable=False, max_length=500, verbose_name="IT/Software/Networking knowledge, as well as whether one's work involves these topics.")),
                ('linux', models.TextField(editable=False, max_length=500, verbose_name='Knowledge in Linux System Administration and CLI use.')),
                ('ptero', models.TextField(editable=False, max_length=500, verbose_name='Knowledge of Pterodactyl Panel')),
            ],
            options={
                'verbose_name': 'Admin Application',
                'verbose_name_plural': 'Admin Applications',
            },
            bases=('staffapps.staffapplication',),
        ),
        migrations.CreateModel(
            name='ModeratorApplication',
            fields=[
                ('staffapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staffapps.staffapplication')),
                ('position', models.CharField(default='Mod', editable=False, max_length=100)),
                ('contact_uppers', models.TextField(editable=False, max_length=500, verbose_name='Ability to reach higher-ups')),
            ],
            options={
                'verbose_name': 'Moderator Application',
                'verbose_name_plural': 'Moderator Applications',
            },
            bases=('staffapps.staffapplication',),
        ),
    ]
