# Generated by Django 4.1.5 on 2023-02-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default='Default', verbose_name='Applicant age')),
                ('time', models.CharField(default='Default', max_length=500, verbose_name='Time Zone and alottable time')),
                ('mc_name', models.CharField(default='Default', max_length=500, verbose_name='Minecraft Username')),
                ('discord_name', models.CharField(default='Default', max_length=500, verbose_name='Discord Username/ID')),
                ('voice_chat', models.BooleanField(default=False, max_length=500, verbose_name='Capable of using Voice Chat?')),
                ('description', models.TextField(default='Default', max_length=500, verbose_name='General self-description')),
                ('modpacks', models.TextField(default='Default', max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft')),
                ('experience', models.TextField(default='Default', max_length=500, verbose_name='Experience on other servers')),
                ('why_join', models.TextField(default='Default', max_length=500, verbose_name='Reasons for wanting to be staff.')),
                ('position', models.CharField(default='Admin', editable=False, max_length=100)),
                ('plugins', models.TextField(default='Default', max_length=500, verbose_name='Knowledge of plugins/server mods and adaptability')),
                ('api', models.TextField(default='Default', max_length=500, verbose_name='Knowledge of server APIs and Minecraft proxies.')),
                ('it_knowledge', models.TextField(default='Default', max_length=500, verbose_name="IT/Software/Networking knowledge, as well as whether one's work involves these topics.")),
                ('linux', models.TextField(default='Default', max_length=500, verbose_name='Knowledge in Linux System Administration and CLI use.')),
                ('ptero', models.TextField(default='Default', max_length=500, verbose_name='Knowledge of Pterodactyl Panel')),
            ],
            options={
                'verbose_name': 'Admin Application',
                'verbose_name_plural': 'Admin Applications',
            },
        ),
        migrations.CreateModel(
            name='ModeratorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default='Default', verbose_name='Applicant age')),
                ('time', models.CharField(default='Default', max_length=500, verbose_name='Time Zone and alottable time')),
                ('mc_name', models.CharField(default='Default', max_length=500, verbose_name='Minecraft Username')),
                ('discord_name', models.CharField(default='Default', max_length=500, verbose_name='Discord Username/ID')),
                ('voice_chat', models.BooleanField(default=False, max_length=500, verbose_name='Capable of using Voice Chat?')),
                ('description', models.TextField(default='Default', max_length=500, verbose_name='General self-description')),
                ('modpacks', models.TextField(default='Default', max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft')),
                ('experience', models.TextField(default='Default', max_length=500, verbose_name='Experience on other servers')),
                ('why_join', models.TextField(default='Default', max_length=500, verbose_name='Reasons for wanting to be staff.')),
                ('position', models.CharField(default='Mod', editable=False, max_length=100)),
                ('contact_uppers', models.TextField(default='Default', max_length=500, verbose_name='Ability to reach higher-ups')),
            ],
            options={
                'verbose_name': 'Moderator Application',
                'verbose_name_plural': 'Moderator Applications',
            },
        ),
    ]
