# Generated by Django 4.1.5 on 2023-02-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapplication',
            name='approved',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='moderatorapplication',
            name='approved',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
