# Generated by Django 3.2.5 on 2022-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='voice_chat',
            field=models.BooleanField(default=False, editable=False, max_length=500, verbose_name='Capable of using Voice Chat?'),
        ),
    ]
