# Generated by Django 3.2.5 on 2022-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapps', '0002_alter_staffapplication_voice_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapplication',
            name='api',
            field=models.TextField(max_length=500, verbose_name='Knowledge of server APIs and Minecraft proxies.'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='it_knowledge',
            field=models.TextField(max_length=500, verbose_name="IT/Software/Networking knowledge, as well as whether one's work involves these topics."),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='linux',
            field=models.TextField(max_length=500, verbose_name='Knowledge in Linux System Administration and CLI use.'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='plugins',
            field=models.TextField(max_length=500, verbose_name='Knowledge of plugins/server mods and adaptability'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='ptero',
            field=models.TextField(max_length=500, verbose_name='Knowledge of Pterodactyl Panel'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='contact_uppers',
            field=models.TextField(max_length=500, verbose_name='Ability to reach higher-ups'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='age',
            field=models.IntegerField(verbose_name='Applicant age'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='description',
            field=models.TextField(max_length=500, verbose_name='General self-description'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='discord_name',
            field=models.CharField(max_length=500, verbose_name='Discord Username/ID'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='experience',
            field=models.TextField(max_length=500, verbose_name='Experience on other servers'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='mc_name',
            field=models.CharField(max_length=500, verbose_name='Minecraft Username'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='modpacks',
            field=models.TextField(max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='time',
            field=models.CharField(max_length=500, verbose_name='Time Zone and alottable time'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='voice_chat',
            field=models.BooleanField(default=False, max_length=500, verbose_name='Capable of using Voice Chat?'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='why_join',
            field=models.TextField(max_length=500, verbose_name='Reasons for wanting to be staff.'),
        ),
    ]
