# Generated by Django 4.2.7 on 2024-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffapps", "0003_staffapplicationfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatedStaffApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_fields",
                    models.ManyToManyField(
                        help_text="A list of created Form Fields that will be used in this Staff Application.",
                        to="staffapps.staffapplicationfield",
                        verbose_name="Form Fields",
                    ),
                ),
            ],
        ),
    ]
