# Generated by Django 3.2.5 on 2022-12-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapps', '0003_auto_20221216_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapplication',
            name='position',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
