# Generated by Django 4.1.5 on 2023-01-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapps', '0004_alter_adminapplication_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapplication',
            name='position',
            field=models.CharField(default='Admin', editable=False, max_length=100),
        ),
    ]
