# Generated by Django 4.2.7 on 2024-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffapps", "0006_submittedstaffapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffapplicationfield",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="The order that this field will appear in forms it is added to.",
                verbose_name="Priority",
            ),
        ),
    ]
