# Generated by Django 4.2.7 on 2024-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffapps", "0007_staffapplicationfield_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedstaffapplication",
            name="submitted_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2024-06-04 00:00",
                verbose_name="Originally Sent",
            ),
            preserve_default=False,
        ),
    ]
