# Generated by Django 4.2.7 on 2024-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffapps", "0008_submittedstaffapplication_submitted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedstaffapplication",
            name="approved",
            field=models.CharField(
                choices=[("A", "Approved"), ("D", "Denied"), ("P", "Pending")],
                default="P",
                max_length=1,
            ),
        ),
    ]
