# Generated by Django 4.2.7 on 2024-07-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffapps", "0010_alter_submittedstaffapplication_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="createdstaffapplication",
            options={
                "verbose_name": "Created Staff Application",
                "verbose_name_plural": "Created Staff Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="staffapplicationfield",
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="submittedstaffapplication",
            options={
                "permissions": [
                    (
                        "approval_submittedstaffapplication",
                        "Can approve or deny Submitted Staff Applications",
                    )
                ],
                "verbose_name": "Submitted Staff Application",
                "verbose_name_plural": "Submitted Staff Applications",
            },
        ),
    ]
