# Generated by Django 3.2.5 on 2022-08-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='none', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField()),
                ('player_names', models.TextField(max_length=1500)),
                ('server', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='raptormc.server')),
            ],
        ),
    ]
