# Generated by Django 4.1.5 on 2023-01-24 10:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformativeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('name', models.CharField(default='Default', max_length=50, verbose_name='Content Name')),
                ('content', ckeditor.fields.RichTextField(default='', max_length=15000, verbose_name='Content')),
            ],
            options={
                'verbose_name': ('Informative Text',),
                'verbose_name_plural': 'Informative Texts',
            },
        ),
    ]
