# Generated by Django 3.2.5 on 2022-08-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_state',
            field=models.BooleanField(default=False),
        ),
    ]
