# Generated by Django 4.1.5 on 2023-02-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='The name of your website and/or network', max_length=100, verbose_name='Website/Network Name')),
                ('main_color', models.CharField(default='#00192d', help_text='The hex color code used for the lower body of the website', max_length=7, verbose_name='Main Color')),
                ('secondary_color', models.CharField(default='#00233c', help_text='The hex color code used for the upper body of the website, layered underneath server buttons', max_length=7, verbose_name='Secondary Color')),
                ('branding_image', models.ImageField(help_text='The image displayed in the website Navigation Bar as a link to the homepage. Optimal size for this image is w800xh200.', upload_to='branding', verbose_name='Branding Image')),
                ('background_image', models.ImageField(help_text='The image displayed layered behind server buttons. This image will cover the defined Secondary Color if used. Optimal size for this image  is 1920x1080 or within the same aspect ratio.', upload_to='background', verbose_name='Background Image')),
            ],
        ),
    ]
