# Generated by Django 3.2.5 on 2022-08-18 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='server',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='raptormc.server'),
        ),
    ]
