# Generated by Django 4.1.5 on 2023-02-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativetext',
            name='content',
            field=models.CharField(default='', max_length=15000, verbose_name='Content'),
        ),
    ]
