# Generated by Django 3.2.5 on 2023-01-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playername',
            name='server',
        ),
        migrations.DeleteModel(
            name='PlayerCount',
        ),
        migrations.DeleteModel(
            name='PlayerName',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
