# Generated by Django 3.2.5 on 2022-09-10 03:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinformation',
            name='server_banned_items',
            field=ckeditor.fields.RichTextField(default='Server-specific Banned Items', max_length=1500, verbose_name='Server-specific Banned Items'),
        ),
        migrations.AlterField(
            model_name='serverinformation',
            name='server_vote_links',
            field=ckeditor.fields.RichTextField(default='Server-specific Vote Links', max_length=1500, verbose_name='Voting Site Links'),
        ),
    ]
