# Generated by Django 3.2.5 on 2022-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0002_auto_20221021_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='modpack_picture',
            field=models.ImageField(blank=True, upload_to='modpack_pictures'),
        ),
    ]
