# Generated by Django 3.2.5 on 2022-08-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0002_alter_playerdata_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdata',
            name='player_names',
        ),
        migrations.CreateModel(
            name='PlayerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('server', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='raptormc.playerdata')),
            ],
        ),
    ]
