# Generated by Django 4.1.5 on 2023-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0002_siteinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'verbose_name': ('Site Information',), 'verbose_name_plural': 'Site Information'},
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='brand_name',
            field=models.CharField(default='Default', help_text='The name of your website and/or network', max_length=100, verbose_name='Website/Network Name'),
        ),
    ]
