# Generated by Django 3.2.5 on 2022-09-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0002_auto_20220909_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativetext',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
