# Generated by Django 4.1.5 on 2023-02-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0003_alter_siteinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='background_image',
            field=models.ImageField(blank=True, help_text='The image displayed layered behind server buttons. This image will cover the defined Secondary Color if used. Optimal size for this image  is 1920x1080 or within the same aspect ratio.', upload_to='background', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='branding_image',
            field=models.ImageField(blank=True, help_text='The image displayed in the website Navigation Bar as a link to the homepage. Optimal size for this image is w800xh200.', upload_to='branding', verbose_name='Branding Image'),
        ),
    ]
