# Generated by Django 3.2.5 on 2022-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0003_informativetext_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinformation',
            name='in_maintenance',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
    ]
