# Generated by Django 3.2.5 on 2022-08-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0003_auto_20220818_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='raptormc.server'),
        ),
        migrations.AlterField(
            model_name='playername',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='raptormc.server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='none', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_state',
            field=models.BooleanField(default=False),
        ),
    ]
