# Generated by Django 3.2.5 on 2022-11-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0003_server_modpack_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='modpack_version',
            field=models.CharField(default='1.0', max_length=100, verbose_name='Modpack Version'),
        ),
    ]
