# Generated by Django 3.2.5 on 2022-10-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0004_serverinformation_in_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinformation',
            name='modpack_name',
            field=models.CharField(default='Unnamed Modpack', max_length=100, verbose_name='Modpack Name'),
        ),
    ]
