# Generated by Django 3.2.5 on 2022-11-24 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raptormc', '0004_server_modpack_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='discord_username',
        ),
        migrations.CreateModel(
            name='DiscordUserInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('pub_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='discord_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='raptormc.discorduserinfo'),
        ),
    ]
