# Generated by Django 4.1.5 on 2023-02-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0004_alter_siteinformation_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='The name of this Navigation Link. Will be displayed on the website', max_length=100, verbose_name='Navigation Link Name')),
                ('url', models.URLField(default='/', help_text='The link this Navigation Link will take the user to', max_length=250, verbose_name='Navigation URL')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this Navigation Link will appear on the website', verbose_name='Enabled')),
            ],
            options={
                'verbose_name': ('Navigation Link',),
                'verbose_name_plural': 'Navigation Links',
            },
        ),
    ]
