# Generated by Django 4.1.5 on 2023-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0005_navbarlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='new_tab',
            field=models.BooleanField(default=False, help_text='If this is True, this link will open in a new tab.', verbose_name='Opens in New Tab'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this Navigation Link will appear on the website.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='name',
            field=models.CharField(default='Default', help_text='The name of this Navigation Link. Will be displayed on the website.', max_length=100, verbose_name='Navigation Link Name'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='url',
            field=models.URLField(default='/', help_text='The link this Navigation Link will take the user to.', max_length=250, verbose_name='Navigation URL'),
        ),
    ]
