# Generated by Django 3.2.5 on 2022-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0005_alter_playername_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playername',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
