# Generated by Django 4.1.5 on 2023-02-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0006_navbarlink_new_tab_alter_navbarlink_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarDropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='The name of this Navigation Dropdown. Will be displayed on the website.', max_length=100, verbose_name='Navigation Link Name')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this Navigation Link will appear on the website.', verbose_name='Enabled')),
            ],
            options={
                'verbose_name': ('Navigation Link',),
                'verbose_name_plural': 'Navigation Links',
            },
        ),
        migrations.AddField(
            model_name='navbarlink',
            name='parent_dropdown',
            field=models.ForeignKey(blank=True, help_text='The Dropdown Menu this link is attached to. This is not required', null=True, on_delete=django.db.models.deletion.CASCADE, to='raptormc.navbardropdown', verbose_name='Dropdown Menu'),
        ),
    ]
