# Generated by Django 4.1.5 on 2023-02-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0007_navbardropdown_navbarlink_parent_dropdown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbardropdown',
            options={'verbose_name': ('Navigation Drodown',), 'verbose_name_plural': 'Navigation Dropdowns'},
        ),
    ]
