# Generated by Django 3.2.5 on 2022-11-24 06:27

from django.db import migrations
import raptormc.managers


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0007_remove_discorduserinfo_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduserinfo',
            managers=[
                ('objects', raptormc.managers.DiscordAuthManager()),
            ],
        ),
    ]
