# Generated by Django 3.2.5 on 2022-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0007_rename_playerdata_playercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('time', models.CharField(max_length=500)),
                ('mc_name', models.CharField(max_length=500)),
                ('discord_name', models.CharField(max_length=500)),
                ('voice_chat', models.BooleanField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('modpacks', models.CharField(max_length=500)),
                ('plugins', models.CharField(max_length=500)),
                ('api', models.CharField(max_length=500)),
                ('IT_knowledge', models.CharField(max_length=500)),
                ('linux', models.CharField(max_length=500)),
                ('ptero', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('why_join', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('time', models.CharField(max_length=500)),
                ('mc_name', models.CharField(max_length=500)),
                ('discord_name', models.CharField(max_length=500)),
                ('voice_chat', models.BooleanField(max_length=500)),
                ('contact_uppers', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('modpacks', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('why_join', models.CharField(max_length=500)),
            ],
        ),
    ]
