# Generated by Django 3.2.5 on 2022-08-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0008_adminapplication_moderatorapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorapplication',
            name='position',
            field=models.CharField(max_length=500, verbose_name='Position applied for'),
        ),
    ]
