# Generated by Django 3.2.5 on 2022-11-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0008_alter_discorduserinfo_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduserinfo',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
