# Generated by Django 4.1.5 on 2023-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0008_alter_navbardropdown_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbardropdown',
            name='priority',
            field=models.IntegerField(default=0, help_text='Controls the order this Navigation Dropdown will be placed in. Lower numbers appear first.', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='navbarlink',
            name='priority',
            field=models.IntegerField(default=0, help_text='Controls the order this Navigation Link will be placed in. Lower numbers appear first.', verbose_name='Priority'),
        ),
    ]
