# Generated by Django 3.2.5 on 2022-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0009_alter_moderatorapplication_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapplication',
            name='IT_knowledge',
            field=models.CharField(max_length=500, verbose_name="IT/Software/Networking knowledge, as well as whether one's work involves these topics."),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='age',
            field=models.IntegerField(verbose_name='Applicant age'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='api',
            field=models.CharField(max_length=500, verbose_name='Knowledge of server APIs and Minecraft proxies.'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='description',
            field=models.CharField(max_length=500, verbose_name='General self-description'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='discord_name',
            field=models.CharField(max_length=500, verbose_name='Discord Username/ID'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='experience',
            field=models.CharField(max_length=500, verbose_name='Experience on other servers'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='linux',
            field=models.CharField(max_length=500, verbose_name='Knowledge in Linux System Administration and CLI use.'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='mc_name',
            field=models.CharField(max_length=500, verbose_name='Minecraft Username'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='modpacks',
            field=models.CharField(max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='plugins',
            field=models.CharField(max_length=500, verbose_name='Knowledge of plugins/server mods and adaptability'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='position',
            field=models.CharField(max_length=500, verbose_name='Position applied for'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='ptero',
            field=models.CharField(max_length=500, verbose_name='Knowledge of Pterodactyl Panel'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='time',
            field=models.CharField(max_length=500, verbose_name='Time Zone and alottable time'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='voice_chat',
            field=models.BooleanField(max_length=500, verbose_name='Capable of using Voice Chat?'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='why_join',
            field=models.CharField(max_length=500, verbose_name='Reasons for wanting to be staff.'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='age',
            field=models.IntegerField(verbose_name='Applicant age'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='contact_uppers',
            field=models.CharField(max_length=500, verbose_name='Ability to reach higher-ups'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='description',
            field=models.CharField(max_length=50, verbose_name='General self-description'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='discord_name',
            field=models.CharField(max_length=500, verbose_name='Discord Username/ID'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='experience',
            field=models.CharField(max_length=500, verbose_name='Experience on other servers'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='mc_name',
            field=models.CharField(max_length=500, verbose_name='Minecraft Username'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='modpacks',
            field=models.CharField(max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='time',
            field=models.CharField(max_length=500, verbose_name='Time Zone and alottable time'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='voice_chat',
            field=models.BooleanField(max_length=500, verbose_name='Capable of Voice Chat?'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='why_join',
            field=models.CharField(max_length=500, verbose_name='Reasons for wanting to be stff'),
        ),
    ]
