# Generated by Django 3.2.5 on 2022-11-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0009_alter_discorduserinfo_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduserinfo',
            options={'verbose_name': 'User - Discord OAuth', 'verbose_name_plural': 'Users - Discord OAuth'},
        ),
    ]
