# Generated by Django 4.1.5 on 2023-02-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0009_navbardropdown_priority_navbarlink_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='parent_dropdown',
            field=models.ForeignKey(blank=True, help_text='The Dropdown Menu this link is attached to. This is not required', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nestedlink', to='raptormc.navbardropdown', verbose_name='Dropdown Menu'),
        ),
    ]
