# Generated by Django 3.2.5 on 2022-08-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0010_auto_20220821_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapplication',
            name='IT_knowledge',
            field=models.TextField(max_length=500, verbose_name="IT/Software/Networking knowledge, as well as whether one's work involves these topics."),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='api',
            field=models.TextField(max_length=500, verbose_name='Knowledge of server APIs and Minecraft proxies.'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='description',
            field=models.TextField(max_length=500, verbose_name='General self-description'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='experience',
            field=models.TextField(max_length=500, verbose_name='Experience on other servers'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='linux',
            field=models.TextField(max_length=500, verbose_name='Knowledge in Linux System Administration and CLI use.'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='modpacks',
            field=models.TextField(max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='plugins',
            field=models.TextField(max_length=500, verbose_name='Knowledge of plugins/server mods and adaptability'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='ptero',
            field=models.TextField(max_length=500, verbose_name='Knowledge of Pterodactyl Panel'),
        ),
        migrations.AlterField(
            model_name='adminapplication',
            name='why_join',
            field=models.TextField(max_length=500, verbose_name='Reasons for wanting to be staff.'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='contact_uppers',
            field=models.TextField(max_length=500, verbose_name='Ability to reach higher-ups'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='description',
            field=models.TextField(max_length=50, verbose_name='General self-description'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='experience',
            field=models.TextField(max_length=500, verbose_name='Experience on other servers'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='modpacks',
            field=models.TextField(max_length=500, verbose_name='Knowledge of server modpacks/general Modded Minecraft'),
        ),
        migrations.AlterField(
            model_name='moderatorapplication',
            name='why_join',
            field=models.TextField(max_length=500, verbose_name='Reasons for wanting to be stff'),
        ),
    ]
