# Generated by Django 4.1.5 on 2023-02-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0010_alter_navbarlink_parent_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='parent_dropdown',
            field=models.ForeignKey(blank=True, help_text='The Dropdown Menu this link is attached to. This is not required', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nestedlink', to='raptormc.navbardropdown', verbose_name='Dropdown Menu'),
        ),
    ]
