# Generated by Django 3.2.5 on 2022-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0010_alter_discorduserinfo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discorduserinfo',
            old_name='avatar',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='discorduserinfo',
            name='favorite_modpack',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='discorduserinfo',
            name='minecraft_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='minecraft_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
