# Generated by Django 3.2.5 on 2022-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0011_auto_20220821_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminapplication',
            options={'verbose_name': 'Admin Application', 'verbose_name_plural': 'Admin Applications'},
        ),
        migrations.AlterModelOptions(
            name='moderatorapplication',
            options={'verbose_name': 'Moderator Application', 'verbose_name_plural': 'Moderator Applications'},
        ),
    ]
