# Generated by Django 3.2.5 on 2022-11-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0011_auto_20221124_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduserinfo',
            name='username',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
