# Generated by Django 4.1.5 on 2023-02-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0012_notificationtoast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtoast',
            options={'verbose_name': ('Notification Toast',), 'verbose_name_plural': 'Notification Toasts'},
        ),
    ]
