# Generated by Django 3.2.5 on 2022-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0012_discorduserinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduserinfo',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
