# Generated by Django 3.2.5 on 2022-12-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0013_discorduserinfo_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='discord_info',
        ),
    ]
