# Generated by Django 4.1.5 on 2023-02-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0013_alter_notificationtoast_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtoast',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this Notification will appear on the website', verbose_name='Enabled'),
        ),
    ]
