# Generated by Django 3.2.5 on 2022-12-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0014_remove_userprofileinfo_discord_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminApplication',
        ),
        migrations.DeleteModel(
            name='ModeratorApplication',
        ),
    ]
