# Generated by Django 3.2.5 on 2022-08-26 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0014_alter_userprofileinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='\\w+.\\{1\\}')])),
                ('description', models.CharField(max_length=1500, verbose_name='Server Description')),
                ('modpack_url', models.URLField(verbose_name='Link to Modpack')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raptormc.server')),
            ],
        ),
    ]
