# Generated by Django 4.1.5 on 2023-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0014_notificationtoast_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this page, will be displayed at the top, before the page content.', max_length=100, verbose_name='Name')),
                ('content', models.TextField(default='', help_text='The content of this page.', max_length=15000, verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('show_gameservers', models.BooleanField(default=True, help_text='If this is checked, this page will display Server buttons in the usual location.', verbose_name='Show Servers')),
            ],
            options={
                'verbose_name': ('Page',),
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
