# Generated by Django 4.1.5 on 2023-02-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0015_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='linked_page',
            field=models.ForeignKey(blank=True, help_text='The Page Model that this Navigation Link will lead to. If this is set, then the Navigation URL field will be ignored.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linkedpage', to='raptormc.page', verbose_name='Linked Page'),
        ),
    ]
