# Generated by Django 4.1.5 on 2023-02-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0016_navbarlink_linked_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='url',
            field=models.URLField(default='https://google.com', help_text='The link this Navigation Link will take the user to.', max_length=250, verbose_name='Navigation URL'),
        ),
    ]
