# Generated by Django 4.1.5 on 2023-02-20 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0017_alter_navbarlink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavWidgetBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='The name of this Nav Widget Bar. Only used for internal identification.', max_length=100, verbose_name='Nav Widget Bar Name')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this Nav Widget Bar will appear on the website.', verbose_name='Enabled')),
                ('priority', models.IntegerField(default=0, help_text='Controls the order this Nav Widget Bar will be placed in. Lower numbers appear first.', verbose_name='Priority')),
            ],
            options={
                'verbose_name': ('Navigation Drodown',),
                'verbose_name_plural': 'Navigation Dropdowns',
            },
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='linked_page',
            field=models.ForeignKey(blank=True, help_text='The Page Model that this Navigation Link will lead to. If this is set, then the Navigation URL field will be ignored.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linktopage', to='raptormc.page', verbose_name='Linked Page'),
        ),
        migrations.CreateModel(
            name='NavWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='The name of this Navigation Button. Will be displayed on the website. if a Widget Image is not used.', max_length=100, verbose_name='Navigation Link Name')),
                ('nav_image', models.ImageField(blank=True, help_text='The image used as an identifier/name for this Nav Widget. Optimal size for this image is w250xh72 or within the same aspect ratio.', upload_to='navwidgetimage', verbose_name='Nav Widget Image')),
                ('url', models.URLField(default='https://google.com', help_text='The link this Navigation button will take the user to.', max_length=250, verbose_name='Navigation URL')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this Navigation Button will appear on the website.', verbose_name='Enabled')),
                ('priority', models.IntegerField(default=0, help_text='Controls the order this Navigation Button will be placed in. Lower numbers appear first.', verbose_name='Priority')),
                ('new_tab', models.BooleanField(default=False, help_text='If this is True, this Button will open in a new tab.', verbose_name='Opens in New Tab')),
                ('linked_page', models.ForeignKey(blank=True, help_text='The Page Model that this Navigation Button will lead to. If this is set, then the Navigation URL field will be ignored.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='widgettopage', to='raptormc.page', verbose_name='Linked Page')),
                ('parent_bar', models.ForeignKey(blank=True, help_text='The Nav Widget Bar this link is attached to. A Nav Widget will appear in the default Nav Widget Bar. if one is not specified here', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nestednavwidget', to='raptormc.navwidgetbar', verbose_name='Linked Nav Widget Bar')),
            ],
        ),
    ]
