# Generated by Django 4.1.5 on 2023-02-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0018_navwidgetbar_alter_navbarlink_linked_page_navwidget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navwidget',
            options={'verbose_name': ('Nav Widget',), 'verbose_name_plural': 'Nav Widgets'},
        ),
        migrations.AlterModelOptions(
            name='navwidgetbar',
            options={'verbose_name': ('Nav Widget Bar',), 'verbose_name_plural': 'Nav Widget Bars'},
        ),
    ]
