# Generated by Django 3.2.5 on 2022-08-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0018_alter_serverinformation_server_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinformation',
            name='server_address',
            field=models.CharField(max_length=50),
        ),
    ]
