# Generated by Django 4.1.5 on 2023-02-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0019_alter_navwidget_options_alter_navwidgetbar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='meta_description',
            field=models.CharField(default='', help_text='The description for your website provided in search engine results. This will apply to all pages.', max_length=500, verbose_name='SEO - Meta Description'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='meta_keywords',
            field=models.CharField(default='', help_text='A series of comma-separated values that represent meta keywords used in search engine results. This will apply to all pages.', max_length=500, verbose_name='SEO - Meta Keywords'),
        ),
    ]
