# Generated by Django 3.2.5 on 2022-08-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0020_alter_serverinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playercount',
            options={'verbose_name': 'Player Count', 'verbose_name_plural': 'Player Counts'},
        ),
        migrations.AlterModelOptions(
            name='playername',
            options={'verbose_name': 'Player Name', 'verbose_name_plural': 'Player Names'},
        ),
        migrations.AlterModelOptions(
            name='serverinformation',
            options={'verbose_name': 'Server - Information', 'verbose_name_plural': 'Servers - Information'},
        ),
    ]
