# Generated by Django 3.2.5 on 2022-08-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0021_auto_20220826_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinformation',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Server Description'),
        ),
    ]
