# Generated by Django 4.1.5 on 2023-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0021_page_meta_description_page_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank='true', default='', help_text='The description for this page provided in search engine results. This will apply only to this page, overriding default.', max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank='true', default='', help_text='The comma-separated keywords for this page used in search engine results. This will apply only to this page, overriding default.', max_length=500, verbose_name='SEO Keywords'),
        ),
    ]
