# Generated by Django 4.1.5 on 2023-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0022_alter_page_meta_description_alter_page_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='The description for this page provided in search engine results. This will apply only to this page, overriding default.', max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='The comma-separated keywords for this page used in search engine results. This will apply only to this page, overriding default.', max_length=500, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='The description for your website provided in search engine results. This will apply to all pages that do not override.', max_length=500, verbose_name='SEO - Meta Description'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='A series of comma-separated values that represent meta keywords used in search engine results. This will apply to all pages that do not override.', max_length=500, verbose_name='SEO - Meta Keywords'),
        ),
    ]
