# Generated by Django 3.2.5 on 2022-08-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0023_auto_20220827_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformativeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('general', 'General Info'), ('rules', 'Rule Block'), ('banneditems', 'Banned Items Block')], default='general', max_length=20, verbose_name='Content Type')),
                ('content', models.TextField(default='', max_length=1000, verbose_name='Content')),
            ],
        ),
    ]
