# Generated by Django 4.2.3 on 2023-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0023_alter_page_meta_description_alter_page_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='The image displayed in OpenGraph embeds, such as when a link is pasted to a Discord Channel or a Twitter post. This should be a 1x1 image.', upload_to='avatar', verbose_name='Avatar Image'),
        ),
    ]
