# Generated by Django 3.2.5 on 2022-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0024_informativetext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informativetext',
            name='content_type',
        ),
        migrations.AddField(
            model_name='serverinformation',
            name='server_banned_items',
            field=models.TextField(default='Server-specific Banned Items', max_length=500, verbose_name='Server-specific Banned Items'),
        ),
        migrations.AddField(
            model_name='serverinformation',
            name='server_rules',
            field=models.TextField(default='Server-specific Rules', max_length=1500, verbose_name='Server-Specific Rules'),
        ),
    ]
