# Generated by Django 4.2.3 on 2023-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0024_siteinformation_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='ico_image',
            field=models.ImageField(blank=True, help_text='Icon file used for Favicon. Automatically generated from Avatar', upload_to='ico', verbose_name='Ico Image'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='The image displayed in OpenGraph embeds, such as when a link is pasted to a Discord Channel or a Twitter post. This should be a 1x1 image. This will also be used as your Favicon, after being converted to a .ico file.', upload_to='avatar', verbose_name='Avatar Image'),
        ),
    ]
