# Generated by Django 3.2.5 on 2022-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0025_auto_20220831_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informativetext',
            options={'verbose_name': ('Informative Text',), 'verbose_name_plural': 'Informative Texts'},
        ),
        migrations.AddField(
            model_name='informativetext',
            name='name',
            field=models.CharField(default='Default', max_length=50, verbose_name='Content Name'),
        ),
    ]
