# Generated by Django 4.2.3 on 2023-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0025_siteinformation_ico_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='time_last_saved',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
