# Generated by Django 3.2.5 on 2022-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0026_auto_20220831_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativetext',
            name='content',
            field=models.TextField(default='', max_length=15000, verbose_name='Content'),
        ),
    ]
