# Generated by Django 4.2.3 on 2023-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0026_siteinformation_time_last_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallSiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_image', models.ImageField(blank=True, help_text='Icon file used for Favicon. Automatically generated from Avatar', upload_to='ico', verbose_name='Ico Image')),
            ],
            options={
                'verbose_name': ('Small Site Information',),
                'verbose_name_plural': 'Small Site Information',
            },
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='ico_image',
        ),
    ]
