# Generated by Django 3.2.5 on 2022-08-31 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0027_alter_informativetext_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativetext',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=15000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='serverinformation',
            name='modpack_description',
            field=ckeditor.fields.RichTextField(default='Modpack Description', max_length=1500, verbose_name='Modpack Description'),
        ),
        migrations.AlterField(
            model_name='serverinformation',
            name='server_banned_items',
            field=ckeditor.fields.RichTextField(default='Server-specific Banned Items', max_length=500, verbose_name='Server-specific Banned Items'),
        ),
        migrations.AlterField(
            model_name='serverinformation',
            name='server_description',
            field=ckeditor.fields.RichTextField(default='Server Description', max_length=1500, verbose_name='Server Description'),
        ),
        migrations.AlterField(
            model_name='serverinformation',
            name='server_rules',
            field=ckeditor.fields.RichTextField(default='Server-specific Rules', max_length=1500, verbose_name='Server-Specific Rules'),
        ),
    ]
