# Generated by Django 4.2.3 on 2023-07-18 22:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0027_smallsiteinformation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallsiteinformation',
            options={'verbose_name': ('Site Information',), 'verbose_name_plural': 'Site Information'},
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='time_last_saved',
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='avatar_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='The image displayed in OpenGraph embeds, such as when a link is pasted to a Discord Channel or a Twitter post. This should be a 1x1 image. This will also be used as your Favicon, after being converted to a .ico file.', keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='avatar', verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='smallsiteinformation',
            name='ico_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='ICO', keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='ico', verbose_name='Avatar Image'),
        ),
    ]
