# Generated by Django 3.2.5 on 2022-09-05 07:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0028_auto_20220831_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinformation',
            name='server_vote_links',
            field=ckeditor.fields.RichTextField(default='Server-specific Vote Links', max_length=500, verbose_name='Voting Site Links'),
        ),
    ]
