# Generated by Django 4.2.3 on 2023-07-19 22:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0030_alter_smallsiteinformation_ico_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='The image displayed in OpenGraph embeds, such as when a link is pasted to a Discord Channel or a Twitter post. This should be a 1x1 image. This will also be used as your Favicon, after being converted to a .ico file.', upload_to='avatar', verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='smallsiteinformation',
            name='ico_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='ICO', keep_meta=True, quality=50, scale=None, size=[64, 64], upload_to='ico'),
        ),
    ]
