# Generated by Django 4.2.3 on 2023-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0035_alter_smallsiteinformation_ico_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.BooleanField(default=True, help_text='Whether the default Announcement page is enabled or not.', verbose_name='Announcements Page')),
                ('rules', models.BooleanField(default=True, help_text='Whether the default Rules page is enabled or not.', verbose_name='Rules Page')),
                ('banned_items', models.BooleanField(default=True, help_text='Whether the default Banned Items page is enabled or not.', verbose_name='Banned Items Page')),
                ('voting', models.BooleanField(default=True, help_text='Whether the default Vote for Us page is enabled or not.', verbose_name='Voting Page')),
                ('joining', models.BooleanField(default=True, help_text='Whether the default How to Join page is enabled or not.', verbose_name='How to Join Page')),
                ('staff_apps', models.BooleanField(default=True, help_text='Whether the default Staff Applications page is enabled or not.', verbose_name='Staff Applications Page')),
                ('members', models.BooleanField(default=True, help_text='Whether the default Site Members page is enabled or not.', verbose_name='Site Members Page')),
            ],
            options={
                'verbose_name': ('Informative Text',),
                'verbose_name_plural': 'Informative Texts',
            },
        ),
    ]
