# Generated by Django 4.2.3 on 2023-07-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0036_defaultpages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultpages',
            options={'verbose_name': ('Default Pages',), 'verbose_name_plural': 'Default Pages'},
        ),
    ]
