# Generated by Django 4.2.3 on 2023-07-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0037_alter_defaultpages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='use_main_color',
            field=models.BooleanField(default=True, help_text="If this is checked, the Main Color chosen above will be used on the website. If not, the color determined from the user's current Light/Dark theme choice will be used instead.", verbose_name='Use Main Color'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='use_secondary_color',
            field=models.BooleanField(default=True, help_text="If this is checked, the Secondary Color chosen above will be used on the website. If not, the color determined from the user's current Light/Dark theme choice will be used instead. If you are using a Background Image, that will always take precedence.", verbose_name='Use Secondary Color'),
        ),
    ]
