# Generated by Django 4.2.3 on 2023-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0038_siteinformation_use_main_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'verbose_name': ('Site Settings',), 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email to be linked with a mailto in the footer of the website.', max_length=500, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='enable_footer',
            field=models.BooleanField(default=True, help_text='If this is checked, the footer will be enabled', verbose_name='Enable Footer'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='enable_footer_contact',
            field=models.BooleanField(default=True, help_text='If this is checked, a mailto link will appear in the footer, addressed to the defined contact email.', verbose_name='Enable Email in Footer'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='enable_footer_credit',
            field=models.BooleanField(default=True, help_text="If this is checked, link to Zediious' GitHub profile will appear in the footer. This has no effect if Enable Footer is disabled.", verbose_name='Enable Credits in Footer'),
        ),
    ]
