# Generated by Django 4.2.5 on 2023-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0001_squashed_0039_alter_siteinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_css',
            field=models.CharField(blank=True, default='', help_text='Custom style sheet that will only apply on this page. This will apply only to this page, overriding any defaults.', max_length=30000, verbose_name='Page CSS'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_js',
            field=models.CharField(blank=True, default='', help_text='Custom Javascript that will only apply on this page.', max_length=30000, verbose_name='Page JavaScript'),
        ),
    ]
