# Generated by Django 4.2.5 on 2023-10-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0040_page_page_css_page_page_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='navwidget',
            name='tooltip',
            field=models.CharField(blank=True, default='', help_text='A tooltip with custom text that will be displayed when the widget is hovered over, or held down on a touchscreen.', max_length=300, verbose_name='Widget Tooltip'),
        ),
    ]
