# Generated by Django 4.2.7 on 2023-11-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0042_alter_siteinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'permissions': [('panel', 'Can access the Control Panel Homepage'), ('discord_bot', 'Can access the Discord Bot control panel'), ('server_actions', 'Can access the Server Actions menu'), ('reporting', 'Can access Reporting'), ('settings', 'Can access settings (DANGEROUS!)')], 'verbose_name': ('Site Settings',), 'verbose_name_plural': 'Site Settings'},
        ),
    ]
