# Generated by Django 4.2.7 on 2023-11-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0043_alter_siteinformation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='require_login_for_user_list',
            field=models.BooleanField(default=True, help_text='If this is checked, users will need to create an account and, log in before they can access the Site Members list.', verbose_name='Require login for Site Members'),
        ),
    ]
