# Generated by Django 4.2.7 on 2023-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0044_siteinformation_require_login_for_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='enable_server_query',
            field=models.BooleanField(default=True, help_text="If this is un-checked, the address/port of created Servers will NOT be, queried for state and player data. Each server's information will still be displayed on the website as normal, however the Player Counts section of the Header Box will no longer appear.", verbose_name='Enable server querying and player counts section'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='server_pagination_count',
            field=models.IntegerField(default=6, help_text='How many server buttons will appear per page. If the amount of Servers exceeds this amount, a set if Next and Previous buttons will appear to cycle between pages of created servers.', verbose_name='Server button pagination count'),
        ),
    ]
