# Generated by Django 4.2.7 on 2023-11-18 23:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0049_alter_navwidget_nav_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navwidget',
            name='nav_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='The image used as an identifier/name for this Nav Widget. Optimal size for this image is w250xh72 or within the same aspect ratio.', keep_meta=False, quality=100, scale=None, size=[250, 72], upload_to='navwidgetimage', verbose_name='Nav Widget Image'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='avatar_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='The image displayed in OpenGraph embeds, such as when a link is pasted to a Discord Channel or a Twitter post. This should be a 1x1 image. This will also be used as your Favicon, after being converted to a .ico file.', keep_meta=False, quality=100, scale=None, size=[500, 500], upload_to='avatar', verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='The image displayed layered behind server buttons. This image will cover the defined Secondary Color if used. Optimal size for this image  is 1920x1080 or within the same aspect ratio.', keep_meta=False, quality=100, scale=None, size=[1920, 1080], upload_to='background', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='branding_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='The image displayed in the website Navigation Bar as a link to the homepage. Optimal size for this image is w800xh200.', keep_meta=False, quality=100, scale=None, size=[550, 170], upload_to='branding', verbose_name='Branding Image'),
        ),
    ]
