# Generated by Django 4.2.7 on 2023-11-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0054_alter_siteinformation_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpages',
            name='onboarding',
            field=models.BooleanField(default=True, help_text='Pages that contain all information about each server.', verbose_name='Onboarding Pages'),
        ),
    ]
