# Generated by Django 4.2.7 on 2023-12-03 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0057_alter_defaultpages_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='server_pagination_count',
            field=models.IntegerField(default=6, help_text='How many server buttons will appear per page. If the amount of Servers exceeds this amount, a set if Next and Previous buttons will appear to cycle between pages of created servers.', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Server buttons per-page'),
        ),
    ]
