# Generated by Django 4.2.7 on 2023-12-03 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0058_alter_siteinformation_server_pagination_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='server_pagination_count',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=6, help_text='How many server buttons will appear per page. If the amount of Servers exceeds this amount, a set if Next and Previous buttons will appear to cycle between pages of created servers.', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Server buttons per-page'),
        ),
    ]
