# Generated by Django 4.2.7 on 2023-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0060_alter_siteinformation_server_pagination_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpages',
            name='donations',
            field=models.BooleanField(default=True, help_text='Whether the Donations system/pages are enabled or not.', verbose_name='Donations Pages'),
        ),
    ]
