# Generated by Django 4.2.7 on 2023-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0061_defaultpages_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='navigation_from_top',
            field=models.BooleanField(default=True, help_text='If this is checked, the Navigation popup will come from the top of the screen rather than the left.', verbose_name='Navigation popup from top of screen.'),
        ),
    ]
