# Generated by Django 4.2.7 on 2023-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0063_alter_siteinformation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='send_donation_email',
            field=models.BooleanField(default=True, help_text='If this is checked, emails will be sent to donators if they are logged into an account when donating.', verbose_name='Send emails upon successful donations.'),
        ),
    ]
