# Generated by Django 4.2.7 on 2023-12-18 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0064_siteinformation_send_donation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='donation_goal',
            field=models.IntegerField(default=1, help_text='The monthly donation goal in USD. This will reset at the beginning of every month.', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Monthly Donation Goal.'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='show_donation_goal',
            field=models.BooleanField(default=True, help_text='Whether the monthly donation goal will appear on the website', verbose_name='Show Monthly Donation Goal.'),
        ),
    ]
