# Generated by Django 4.2.7 on 2023-12-18 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0065_siteinformation_donation_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='donation_goal_progress',
            field=models.IntegerField(default=0, help_text='The total donation amount since the beginning of the current month.', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='Monthly Donation Goal Progress.'),
        ),
    ]
