# Generated by Django 4.2.7 on 2023-12-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0066_siteinformation_donation_goal_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='show_recent_donators',
            field=models.BooleanField(default=True, help_text='Whether the the last 5 donators will appear on the donations page, along with the package they donated for.', verbose_name='Show Recent Donators.'),
        ),
    ]
