# Generated by Django 4.2.7 on 2023-12-22 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0067_siteinformation_show_recent_donators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='donation_goal',
            field=models.IntegerField(default=1, help_text='The monthly donation goal. This will reset at the beginning of every month.', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Monthly Donation Goal.'),
        ),
    ]
