# Generated by Django 4.2.7 on 2023-12-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0068_alter_siteinformation_donation_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='donation_currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('cad', 'Canadian Dollar'), ('mxn', 'Mexican Peso'), ('gbp', 'Pound'), ('eur', 'Euro')], default='usd', help_text='The currency used when accepting donations.', max_length=10, verbose_name='Donation Currency'),
        ),
    ]
