# Generated by Django 4.2.7 on 2023-12-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptormc', '0069_siteinformation_donation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='paypal_enabled',
            field=models.BooleanField(default=True, help_text='If this is checked, PayPal will be given as an option to pay when Donating. At least one Payment Gateway must be enabled.', verbose_name='PayPal Payment Gateway'),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='stripe_enabled',
            field=models.BooleanField(default=True, help_text='If this is checked, Stripe will be given as an option to pay when Donating. At least one Payment Gateway must be enabled.', verbose_name='Stripe Payment Gateway'),
        ),
        migrations.AlterField(
            model_name='defaultpages',
            name='donations',
            field=models.BooleanField(default=False, help_text='Whether the Donations system/pages are enabled or not.', verbose_name='Donations Pages'),
        ),
    ]
