# Generated by Django 4.2.7 on 2024-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0072_alter_siteinformation_server_maintenance_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinformation",
            name="server_maintenance_message",
            field=models.CharField(
                blank=True,
                default="Server is in maintenance mode!",
                help_text="Text shown in tooltip while hovering over a server in maintenance mode's status icon. If left blank, no tooltip will appear.",
                max_length=500,
                null=True,
                verbose_name="Server Maintenance Message",
            ),
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="server_offline_message",
            field=models.CharField(
                blank=True,
                default="Server is offline!",
                help_text="Text shown in tooltip while hovering over an offline server status icon. If left blank, no tooltip will appear.",
                max_length=500,
                null=True,
                verbose_name="Server Offline Message",
            ),
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="server_online_message",
            field=models.CharField(
                blank=True,
                default="Server is online!",
                help_text="Text shown in tooltip while hovering over an online server status icon. If left blank, no tooltip will appear.",
                max_length=500,
                null=True,
                verbose_name="Server Online Message",
            ),
        ),
    ]
