# Generated by Django 4.2.7 on 2024-05-28 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0073_alter_siteinformation_server_maintenance_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinformation",
            name="query_delay",
            field=models.IntegerField(
                default=1,
                help_text="The time in minutes to wait between server queries. Every time the server box is loaded, servers will be checked if a query can occur. This determines how long that delay is.",
                validators=[
                    django.core.validators.MaxValueValidator(60),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Time between Server Queries",
            ),
        ),
    ]
