# Generated by Django 4.2.7 on 2024-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0075_siteinformation_branding_image_svg"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinformation",
            name="use_svg_brand",
            field=models.BooleanField(
                default=False,
                help_text="If this is checked, the SVG Branding Image will be used instead of the. uploaded raster Branding Image.",
                verbose_name="Use SVG Branding Image",
            ),
        ),
    ]
