# Generated by Django 4.2.7 on 2024-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0076_siteinformation_use_svg_brand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteinformation",
            options={
                "permissions": [
                    ("panel", "Can access the Control Panel Homepage"),
                    ("discord_bot", "Can access the Discord Bot control panel"),
                    (
                        "server_import_export",
                        "Can access the Server Import/Export menu",
                    ),
                    ("server_list", "Can access the list of created servers"),
                    ("server_update", "Can edit the list of created servers"),
                    ("server_maintenance", "Can toggle a server's maintenance status."),
                    ("server_archive", "Can toggle a server's archive status."),
                    ("reporting", "Can access Reporting"),
                    ("donations", "Can access Donations"),
                    ("settings", "Can access settings (DANGEROUS!)"),
                ],
                "verbose_name": ("Site Settings",),
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="use_svg_brand",
            field=models.BooleanField(
                default=False,
                help_text="If this is checked, the SVG Branding Image will be used instead of the uploaded raster Branding Image.",
                verbose_name="Use SVG Branding Image",
            ),
        ),
    ]
