# Generated by Django 4.2.7 on 2024-06-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0077_alter_siteinformation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteinformation",
            options={
                "permissions": [
                    ("panel", "Can access the Control Panel Homepage"),
                    ("discord_bot", "Can access the Discord Bot control panel"),
                    (
                        "server_import_export",
                        "Can access the Server Import/Export menu",
                    ),
                    ("server_list", "Can access the list of created servers"),
                    ("server_update", "Can edit the list of created servers"),
                    ("server_maintenance", "Can toggle a server's maintenance status."),
                    ("server_archive", "Can toggle a server's archive status."),
                    ("server_delete", "Can permanently delete a server."),
                    ("reporting", "Can access Reporting"),
                    ("donations", "Can access Donations"),
                    ("settings", "Can access settings (DANGEROUS!)"),
                ],
                "verbose_name": ("Site Settings",),
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
