# Generated by Django 4.2.7 on 2024-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0081_alter_siteinformation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_css",
            field=models.FileField(
                blank=True,
                help_text="Custom style sheet that will only apply on this page. This will apply only to this page, overriding any defaults.",
                null=True,
                upload_to="page_css",
                verbose_name="Page CSS",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="page_js",
            field=models.FileField(
                blank=True,
                help_text="Custom Javascript that will only apply on this page.",
                null=True,
                upload_to="page_js",
                verbose_name="Page JavaScript",
            ),
        ),
    ]
