# Generated by Django 4.2.7 on 2024-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0084_alter_siteinformation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtoast",
            name="message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The message for this notification",
                max_length=15000,
                verbose_name="Message",
            ),
        ),
    ]
