# Generated by Django 4.2.7 on 2024-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0088_alter_siteinformation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteinformation",
            options={
                "permissions": [
                    ("panel", "Can access the Control Panel Homepage"),
                    ("discord_bot_panel", "Can access the Discord Bot control panel"),
                    ("reporting", "Can access Reporting"),
                    ("settings", "Can access settings (DANGEROUS!)"),
                ],
                "verbose_name": ("Site Settings",),
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
