# Generated by Django 4.2.7 on 2025-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0090_informativetext_content_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informativetext",
            name="content_header",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If left blank, the default header will be used.",
                max_length=100,
                null=True,
                verbose_name="Header",
            ),
        ),
    ]
