# Generated by Django 4.2.7 on 2025-05-18 22:54

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("raptormc", "0091_alter_informativetext_content_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinformation",
            name="background_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                help_text="The image displayed layered behind server buttons. This image will be covered by the defined Secondary Color if used. Image resized to 1920x1080 after uploading.",
                keep_meta=False,
                quality=90,
                scale=None,
                size=[1920, 1080],
                upload_to="background",
                verbose_name="Background Image",
            ),
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="secondary_color",
            field=models.CharField(
                default="#00233c",
                help_text="The hex color code used for the upper body of the website, layered underneath server buttons. If you are using a Background Image, that will be overridden by this color.",
                max_length=7,
                verbose_name="Secondary Color",
            ),
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="use_secondary_color",
            field=models.BooleanField(
                default=True,
                help_text="If this is checked, the Secondary Color chosen above will be used on the website. If you are using a Background Image, that will be overridden by this color.",
                verbose_name="Use Secondary Color",
            ),
        ),
    ]
