# Generated by Django 4.1.5 on 2023-01-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameservers', '0004_server_discord_modpack_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(default='None', max_length=200, verbose_name='Guild Name')),
                ('guild_id', models.IntegerField(default='None', verbose_name='Guild ID')),
                ('total_members', models.IntegerField(default='None', verbose_name='Total Members')),
                ('online_members', models.IntegerField(default='None', verbose_name='Online Members')),
            ],
            options={
                'verbose_name': 'Discord Guild',
                'verbose_name_plural': 'Discord Guilds',
            },
        ),
        migrations.CreateModel(
            name='GlobalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='None', max_length=100, verbose_name='Author')),
                ('date', models.DateTimeField(default='None', verbose_name='Date')),
                ('message', models.CharField(default='None', max_length=50000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Global Announcement',
                'verbose_name_plural': 'Global Announcements',
            },
        ),
        migrations.CreateModel(
            name='ServerAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='None', max_length=100, verbose_name='Author')),
                ('date', models.DateTimeField(default='None', verbose_name='Date')),
                ('message', models.CharField(default='None', max_length=50000, verbose_name='Message')),
                ('server', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameservers.server')),
            ],
            options={
                'verbose_name': 'Server Announcement',
                'verbose_name_plural': 'Server Announcements',
            },
        ),
    ]
