# Generated by Django 3.2.5 on 2023-01-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameservers', '0003_auto_20230121_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='None', max_length=100, verbose_name='Author')),
                ('date', models.DateField(default='None', verbose_name='Date')),
                ('message', models.CharField(default='None', max_length=50000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='DiscordMemberCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.CharField(default='None', max_length=100, verbose_name='Author')),
                ('online_members', models.DateField(default='None', verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Discord Member Count',
                'verbose_name_plural': 'Discord Member Counts',
            },
        ),
        migrations.CreateModel(
            name='ServerAnnouncement',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='raptorbot.announcement')),
                ('server', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameservers.server')),
            ],
            options={
                'verbose_name': 'Server Announcement',
                'verbose_name_plural': 'Server Announcements',
            },
            bases=('raptorbot.announcement',),
        ),
    ]
