# Generated by Django 4.1.5 on 2023-01-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguild',
            name='guild_id',
            field=models.BigIntegerField(default='None', verbose_name='Guild ID'),
        ),
    ]
