# Generated by Django 4.1.5 on 2023-02-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguild',
            name='invite_link',
            field=models.URLField(blank=True, help_text='The invite link to your Discord Server. This is automatically generated by the Discord Bot', verbose_name='Discord Invite Link'),
        ),
    ]
