# Generated by Django 4.1.5 on 2023-01-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmembercount',
            name='online_members',
            field=models.IntegerField(default='None', verbose_name='Online Members'),
        ),
        migrations.AlterField(
            model_name='discordmembercount',
            name='total_members',
            field=models.IntegerField(default='None', verbose_name='Total Members'),
        ),
    ]
