# Generated by Django 4.1.5 on 2023-01-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0002_alter_discordmembercount_online_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(default='None', max_length=200, verbose_name='Guild Name')),
                ('guild_id', models.IntegerField(default='None', verbose_name='Total Members')),
                ('total_members', models.IntegerField(default='None', verbose_name='Total Members')),
                ('online_members', models.IntegerField(default='None', verbose_name='Online Members')),
            ],
            options={
                'verbose_name': 'Discord Member Count',
                'verbose_name_plural': 'Discord Member Counts',
            },
        ),
        migrations.DeleteModel(
            name='DiscordMemberCount',
        ),
    ]
