# Generated by Django 4.1.5 on 2023-02-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0002_discordguild_invite_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordguild',
            options={'verbose_name': 'Discord Guild', 'verbose_name_plural': 'Discord Guild'},
        ),
    ]
