# Generated by Django 4.1.5 on 2023-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0003_alter_discordguild_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_global_announcements', models.CharField(default='None', max_length=200, verbose_name='Guild Name')),
                ('refresh_server_announcements', models.BigIntegerField(default='None', verbose_name='Guild ID')),
                ('update_members', models.URLField(blank=True, help_text='The invite link to your Discord Server. This is automatically generated by the Discord Bot', verbose_name='Discord Invite Link')),
            ],
            options={
                'verbose_name': 'Discord Bot Tasks',
                'verbose_name_plural': 'Discord Bot Tasks',
            },
        ),
    ]
