# Generated by Django 4.1.5 on 2023-01-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0003_discordguild_delete_discordmembercount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordguild',
            options={'verbose_name': 'Discord Guild', 'verbose_name_plural': 'Discord Guilds'},
        ),
        migrations.AlterField(
            model_name='discordguild',
            name='guild_id',
            field=models.IntegerField(default='None', verbose_name='Guild ID'),
        ),
    ]
