# Generated by Django 4.1.5 on 2023-01-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0004_alter_discordguild_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.CharField(default='None', max_length=100, verbose_name='Date'),
        ),
    ]
