# Generated by Django 4.1.5 on 2023-01-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0005_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default='None', verbose_name='Date'),
        ),
    ]
