# Generated by Django 4.2.5 on 2023-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0005_alter_discordbottasks_refresh_global_announcements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='botinternal-stat', max_length=150)),
                ('time_last_stopped', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Discord Bot Internal',
                'verbose_name_plural': 'Discord Bot Internal',
            },
        ),
    ]
