# Generated by Django 4.2.7 on 2023-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0007_sentembedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentembedmessage',
            name='webhook_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
