# Generated by Django 4.2.7 on 2023-11-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0008_sentembedmessage_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordbottasks',
            name='update_embeds',
            field=models.BooleanField(default=False),
        ),
    ]
