# Generated by Django 4.2.7 on 2023-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0009_discordbottasks_update_embeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentembedmessage',
            name='channel_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
