# Generated by Django 4.2.7 on 2023-12-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raptorbot', '0015_alter_sentembedmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordbottasks',
            name='users_and_roles_to_give',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='discordbottasks',
            name='messages_to_delete',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
