# Generated by Django 4.2.7 on 2023-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationServerCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='', max_length=2000)),
            ],
            options={
                'verbose_name': 'Server Command',
                'verbose_name_plural': 'Server Commands',
            },
        ),
        migrations.CreateModel(
            name='DonationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('commands', models.ManyToManyField(to='donations.donationservercommand', verbose_name='Commands to Send')),
            ],
            options={
                'verbose_name': 'Donation Package',
                'verbose_name_plural': 'Donation Packages',
            },
        ),
    ]
