# Generated by Django 4.2.7 on 2023-12-04 17:58

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpackage',
            name='package_description',
            field=models.CharField(default='Package Description', help_text='A description of this donation package, along with the benefits it will give.', max_length=1500, verbose_name='Package Description'),
        ),
        migrations.AddField(
            model_name='donationpackage',
            name='package_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='An image associated with this donation package that will be displayed on the website. This image will be resized to 250x250 after upload.', keep_meta=False, quality=80, scale=None, size=[250, 250], upload_to='package_pictures', verbose_name='Package Image'),
        ),
    ]
