# Generated by Django 4.2.7 on 2023-12-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0012_alter_server_rcon_address_alter_server_rcon_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0003_donationpackage_servers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpackage',
            name='commands',
            field=models.ManyToManyField(help_text='A list of created Server Commands to send when this package is bought.', to='donations.donationservercommand', verbose_name='Commands to Send.'),
        ),
        migrations.AlterField(
            model_name='donationpackage',
            name='servers',
            field=models.ManyToManyField(help_text='The servers that this package will send commands to.', to='gameservers.server', verbose_name='Servers to send Commands to.'),
        ),
        migrations.CreateModel(
            name='CompletedDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of Donation')),
                ('minecraft_username', models.CharField(help_text='The Minecraft username of the donating user. This will match the Minecraft username of the associated user, if one exists.', max_length=100, verbose_name='Minecraft Username of Donor')),
                ('bought_package', models.ForeignKey(help_text='The package that was bought.', on_delete=django.db.models.deletion.PROTECT, to='donations.donationpackage', verbose_name='Bought Package')),
                ('donating_user', models.ForeignKey(help_text='The user who donated. This will be blank if the donator was not logged in at the time of donation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Donating User')),
            ],
        ),
    ]
