# Generated by Django 4.2.7 on 2023-12-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_completeddonation_donating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpackage',
            name='price',
            field=models.IntegerField(default=0, help_text='The price of this Package.', verbose_name='Price'),
        ),
    ]
