# Generated by Django 4.2.7 on 2023-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donationpackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddonation',
            name='session_id',
            field=models.CharField(default='', help_text='The session ID used when this donation took place', max_length=1000, verbose_name='Session ID'),
        ),
    ]
