# Generated by Django 4.2.7 on 2023-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_completeddonation_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddonation',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether this donation has been finalized and paid for.', verbose_name='Completed'),
        ),
    ]
