# Generated by Django 4.2.7 on 2023-12-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_completeddonation_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpackage',
            name='allow_repeat',
            field=models.BooleanField(default=False, help_text='If this is enabled, this package can be bought multiple times by the same Minecraft username', verbose_name='Allow multiple purchases'),
        ),
    ]
