# Generated by Django 4.2.7 on 2023-12-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donationpackage_allow_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddonation',
            name='discord_username',
            field=models.CharField(blank=True, help_text='The Discord tag of the donating user. This will match the Discord tag of the associated user, if one exists.', max_length=100, null=True, verbose_name='Discord tag of Donor'),
        ),
    ]
