# Generated by Django 4.2.7 on 2023-12-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_completeddonation_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddonation',
            name='sent_commands_count',
            field=models.IntegerField(default=0, help_text='The amount of times commands were sent for this donation.', verbose_name='Times commands were sent'),
        ),
    ]
