# Generated by Django 4.2.7 on 2023-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0012_alter_server_rcon_address_alter_server_rcon_password_and_more'),
        ('donations', '0012_completeddonation_sent_commands_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpackage',
            name='variable_price',
            field=models.BooleanField(default=False, help_text='If this is enabled, users will be able to input any amount they wish to donate above 1 USD.', verbose_name='Variable Price'),
        ),
        migrations.AlterField(
            model_name='donationpackage',
            name='commands',
            field=models.ManyToManyField(blank=True, help_text='A list of created Server Commands to send when this package is bought.', to='donations.donationservercommand', verbose_name='Commands to Send.'),
        ),
        migrations.AlterField(
            model_name='donationpackage',
            name='servers',
            field=models.ManyToManyField(blank=True, help_text='The servers that this package will send commands to.', to='gameservers.server', verbose_name='Servers to send Commands to.'),
        ),
    ]
