# Generated by Django 4.2.7 on 2023-12-17 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_donationpackage_variable_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpackage',
            name='price',
            field=models.IntegerField(default=0, help_text='The price of this Package.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
        ),
    ]
