# Generated by Django 4.2.7 on 2023-12-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_completeddonation_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(default='', help_text='The ID of this Discord Role.', max_length=2000)),
                ('name', models.CharField(default='', help_text='An internal identifer for this role.', max_length=500)),
            ],
            options={
                'verbose_name': 'Discord Role',
                'verbose_name_plural': 'Discord Roles',
            },
        ),
        migrations.AlterField(
            model_name='donationservercommand',
            name='command',
            field=models.CharField(default='', help_text='The command to be sent. Do not include a slash.', max_length=2000),
        ),
    ]
