# Generated by Django 4.2.7 on 2023-12-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_completeddonation_gave_roles_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpackage',
            name='variable_price',
            field=models.BooleanField(default=False, help_text='If this is enabled, users will be able to input any amount they wish to donate above the package price.', verbose_name='Variable Price'),
        ),
    ]
