# Generated by Django 4.2.7 on 2023-12-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_alter_donationpackage_variable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddonation',
            name='paypal_invoice',
            field=models.CharField(blank=True, help_text='The unique ID for the Paypal Invoice generated for this donation.', max_length=1000, null=True, verbose_name='Paypal Invoice ID'),
        ),
        migrations.AlterField(
            model_name='completeddonation',
            name='checkout_id',
            field=models.CharField(blank=True, help_text='The unique ID for the Stripe Checkout session this Donation utilized.', max_length=1000, null=True, verbose_name='Stripe Checkout ID'),
        ),
    ]
