# Generated by Django 4.2.7 on 2023-12-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_completeddonation_paypal_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpackage',
            name='priority',
            field=models.IntegerField(default=0, help_text='The order that this package will appear in the package list..', verbose_name='Priority'),
        ),
    ]
