# Generated by Django 4.2.7 on 2024-06-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0021_donationpackage_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completeddonation",
            options={
                "permissions": [
                    (
                        "resendbenefits_completeddonation",
                        "Can re-send benefits for Completed Donations",
                    )
                ]
            },
        ),
    ]
