# Generated by Django 4.2.7 on 2024-07-13 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0022_alter_completeddonation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completeddonation",
            options={
                "verbose_name": "Completed Donation",
                "verbose_name_plural": "Completion Donations",
            },
        ),
    ]
